from django.conf.urls import url
from .views import (TypeExpenseListView,
                    TypeExpenseCreateView,
                    TypeExpenseUpdateView,
                    TypeExpenseDeleteView,
                    ExpenseCreateView,
                    ExpenseListView,
                    ExpenseUpdateView,
                    ExpenseDeleteView,
                    ExpenseAjaxList,
                    ExpenseGroupAccountView,
                    ExpenseGroupTypeView,
                    ExpenseGroupView)
urlpatterns = [
    url(r'^list/type-expense/$',
        TypeExpenseListView.as_view(),
        name='list_typeexpense'),
    url(r'^create/type-expense$',
        TypeExpenseCreateView.as_view(),
        name='create_typeexpense'),
    url(r'^update/type-expense/(?P<pk>\d+)/$',
        TypeExpenseUpdateView.as_view(),
        name='update_typeexpense'),
    url(r'^delete/type-expense/(?P<pk>\d+)/$',
        TypeExpenseDeleteView.as_view(),
        name='delete_typeexpense'),
    url(r'^crear/$', ExpenseCreateView.as_view(), name='create_expense'),
    url(r'^lista/$', ExpenseListView.as_view(), name='list_expense'),
    url(r'^editar/(?P<pk>\d+)/$',
        ExpenseUpdateView.as_view(),
        name='update_expense'),
    url(r'^delete/(?P<pk>\d+)/$',
        ExpenseDeleteView.as_view(),
        name='delete_expense'),
    url(r'^consulta-gasto/$',
        ExpenseAjaxList.as_view(),
        name='consulta-gasto'),
    url(r'^expense-account/$',
        ExpenseGroupAccountView.as_view(),
        name='group-account'),
    url(r'^agrupacion-gastos/$',
        ExpenseGroupView.as_view(),
        name='group-expense'),
    url(r'^expense-type/$',
        ExpenseGroupTypeView.as_view(),
        name='group-type'),

]
