from django.conf.urls import url
from .views import (AccountListView,
                    AccountCreateView,
                    CreateIncome,
                    TypeIncomeCreateView,
                    TypeIncomeListView,
                    AccountUpdateView,
                    AccountDeleteView,
                    IncomeUpdateView,
                    IncomeListView,
                    IncomeDeleteView,
                    TypeIncomeUpdateView,
                    TypeIncomeDeleteView,
                    IncomesAjaxList,
                    IncomeGroup,
                    IncomeAjaxGroup, IncomeTypeAjaxGroup
                    # Delete1
                    )
urlpatterns = [
    url(r'^lista$',
        AccountListView.as_view(),
        name='list_account'),
    url(r'^create/$',
        AccountCreateView.as_view(),
        name='create_account'),
    url(r'^edit/(?P<pk>\d+)/$',
        AccountUpdateView.as_view(),
        name='update_account'),
    url(r'^delete/(?P<pk>\d+)/$',
        AccountDeleteView.as_view(),
        name='delete_account'),
    # url(r'^delete/(?P<pk>\d+)/$',
    #     Delete1.as_view(),
    #     name='delete_account'),
    url(r'^create/ingreso/$',
        CreateIncome.as_view(),
        name='create_income'),
    url(r'^ingreso/lista/$',
        IncomeListView.as_view(),
        name='list_income'),
    url(r'^consulta-ingreso/$',
        IncomesAjaxList.as_view(),
        name='ajax_list'),
    url(r'^agrupar-ingresos/$',
        IncomeGroup.as_view(),
        name='agrupar_view'),
    url(r'^group-account/$',
        IncomeAjaxGroup.as_view(),
        name='agrupar_ajax'),
    url(r'^group-type/$',
        IncomeTypeAjaxGroup.as_view(),
        name='type_group_ajax'),
    url(r'^edit/ingreso/(?P<pk>\d+)/$',
        IncomeUpdateView.as_view(),
        name='update_income'),
    url(r'^delete/ingreso/(?P<pk>\d+)/$',
        IncomeDeleteView.as_view(),
        name='delete_income'),
    url(r'^crear/tipo-ingreso/$',
        TypeIncomeCreateView.as_view(),
        name='create_type'),
    url(r'^lista/tipo-ingreso/$',
        TypeIncomeListView.as_view(),
        name='list_type'),
    url(r'^editar/tipo-ingreso/(?P<pk>\d+)/$',
        TypeIncomeUpdateView.as_view(),
        name='update_type'),
    url(r'^delete/type/(?P<pk>\d+)/$',
        TypeIncomeDeleteView.as_view(),
        name='delete_type'),

]
